name: Run and display pytest

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Include additional requirements if any

      - name: Run Tests
        run: pytest tests --cov=./slack_api_decorator --cov-report=xml

      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.12' }}
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true